Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/f/fsalerno/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = $(Proxy_path)
environment             = "SCRAM_ARCH=el9_amd64_gcc11"
+JobFlavour             = "nextweek"
executable              = runner_training_Run3_PF_jets_20_LSTM.sh
arguments               = 
output                  = condor/output/training_Run3_PF_jets_20_LSTM.out
error                   = condor/error/training_Run3_PF_jets_20_LSTM.err
log                     = condor/log/training_Run3_PF_jets_20_LSTM.log
queue