Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/f/fsalerno/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = $(Proxy_path)
environment             = "SCRAM_ARCH=el9_amd64_gcc11"
+JobFlavour             = "tomorrow"
executable              = runner_evaluate_multi_PF_submitter.sh
arguments               = 
output                  = condor/output/evaluate_multi_PF_submitter.out
error                   = condor/error/evaluate_multi_PF_submitter.err
log                     = condor/log/evaluate_multi_PF_submitter.log
queue