Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/f/fsalerno/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = $(Proxy_path)
environment             = "SCRAM_ARCH=slc9_amd64_gcc11"
+JobFlavour             = "nextweek"
executable              = runner_GridSearch_base_1_PF_jets_boosted_LSTM.sh
arguments               = 
output                  = condor/output/GridSearch_base_1_PF_jets_boosted_LSTM.out
error                   = condor/error/GridSearch_base_1_PF_jets_boosted_LSTM.err
log                     = condor/log/GridSearch_base_1_PF_jets_boosted_LSTM.log
queue